<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AdresTR\AdresTR.csproj" />
    <ProjectReference Include="..\..\src\AdresTR.Data\AdresTR.Data.csproj" />
  </ItemGroup>

</Project>
