<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    <PackageReference Include="CsCheck" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AdresTR\AdresTR.csproj" />
    <ProjectReference Include="..\..\src\AdresTR.Data\AdresTR.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
