<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <InvariantGlobalization>true</InvariantGlobalization>
    <ContainerRepository>alpercna/adrestr-api</ContainerRepository>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AdresTR\AdresTR.csproj" />
  </ItemGroup>

</Project>
